services:
  - type: web
    name: plant-species-api
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: pip install -r ML/requirements.txt
    startCommand: uvicorn ML.api1forplant_species:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: WEB_CONCURRENCY
        value: "1"
